CHECKPOINTS_DIR = "models"
LOGS_DIR = "logs"
VALID_DATA_DIR = "data/tiles_test/Amsterdam, Netherlands"
DATA_DIR = "data/tiles/Wrocław, PL"
BASE_MODEL_NAME = "hf-internal-testing/tiny-stable-diffusion-pipe"
BATCH_SIZE = 1
DEVICE = "cuda"
EPOCHS = 2
MODEL_NAME = "stable_wroclaw_test"
LEARNING_RAGE = 1e-5
N_COLUMNS = 5
get_unet = None
