CHECKPOINTS_DIR = "models"
LOGS_DIR = "logs"
VALID_DATA_DIR = "data/tiles_test/Amsterdam, Netherlands"
DATA_DIR = "data/tiles/Wrocław, PL"
BASE_MODEL_NAME = 'OFA-Sys/small-stable-diffusion-v0'
BATCH_SIZE = 1
DEVICE = "cuda"
EPOCHS=150
MODEL_NAME = "stable_wroclaw"
LEARNING_RAGE = 1e-5
# CHECKPOINTS_DIR = "models"
# LOGS_DIR = "logs"
# DATA_DIR = "data/celeba/"