[tool.pdm]

[project]
name = "map_generation"
version = "0.0.1"
description = "TODO"
authors = [
    {name = "mprzymus", email = "pzrymus@gmail.com"},
]
dependencies = [
    "torch",
    "diffusers @ git+https://github.com/huggingface/diffusers.git",
    "transformers",
    "datasets>=2.11.0",
    "torchvision",
    "denoising-diffusion-pytorch",
    "pytorch-lightning",
    "requests",
    "mapbox-vector-tile==1.0.0",
    "accelerate>=0.18.0",
    "protobuf==3.20.3",
    "tensorboard>=2.12.2",
    "srai==0.1.1",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
